travis:
  secure:
    BINSTAR_TOKEN: UsH+r6Uf8W/yNrxNZ+5sOttsYfUAC1yAcyTx72IsdVa/YODd2RCucFa2C5CCz9z0D5o0LPm0NGrfPP2YXTjIKbJZs4aQto14nN2yCM5C3Mr6we6uF5yeYT7+9jKyeyWkWHFdCBUgXnBUG/yzR0MdJv3bfWfT6p9e3bOUpuP7vGCMcgU9vqW5oEtAP6x+HMoKLfQM03a/nFnya2jaFNZ/ZF82KvqyczK3U4jzIc1W6nI3SUpwLMV3P1y0GaRPrHw0Nf61RdGjPmG8aQPTtBfvF9xoJ/j/lu4BYFIFefxySpJdAPeKa5xU9grfiU0d23hsHf0EDcOksG+bMB34QFTbbwPfqOWGo3s8p7M0lSO6BXmPvsP7dFBo40F58kV/GwOPWnag2O6DgKaumGg74nP13735Jsrosxkv1udxgb+OLml7YhkzPH2E+yPRpXUigAhC4leBVVwyfnoaL01rSzWFuxQJPVXTh0FuJ27c3bpmCByA0pfT8wdQDU83SChQPZ4rbo0VnCJ2FZzQGOotE+RycVapTgqtCkKDWab8pBuAowVuM87xg+IVFmtLJnIxy3iqImjCFn9f+pzSKLXXmk0NIWDgbcHKWRowT6W2ffSRbhMReeM0kDfT2JNUSYJE8xcrYETAMCaF8PZNF7UHURNwwHmHuptvkWXTADoFStMW7z4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
